[package]
name = "artwork_ejas"
version = "0.1.0"
authors = ["Endre Erős <endre.eros@chalmersindustriteknik.se>"]
edition = "2021"
autotests = false

[dependencies]
z3 = { git = "https://github.com/endre90/z3.rs", branch = "master" }
nanoid = "0.4.0"
json = "0.12.4"
rand = "0.8.5"

[[bin]]
name = "main"
path = "src/main.rs"